// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::driveSpeedController1;
std::shared_ptr<SpeedController> RobotMap::driveSpeedController2;
std::shared_ptr<RobotDrive> RobotMap::driveTankDrive;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveSpeedController1.reset(new Talon(0));
    lw->AddActuator("Drive", "Speed Controller 1", (Talon&) driveSpeedController1);
    
    driveSpeedController2.reset(new Talon(1));
    lw->AddActuator("Drive", "Speed Controller 2", (Talon&) driveSpeedController2);
    
    driveTankDrive.reset(new RobotDrive(driveSpeedController1, driveSpeedController2));
    
    driveTankDrive->SetSafetyEnabled(true);
        driveTankDrive->SetExpiration(0.1);
        driveTankDrive->SetSensitivity(0.5);
        driveTankDrive->SetMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
